---
vs_code_extensions:
  - bbenoist.vagrant
  - DavidAnson.vscode-markdownlint
  - golang.go
  - hashicorp.terraform
  - joaompinto.asciidoctor-vscode
  - ms-azuretools.vscode-docker
  - ms-python.python
  - rust-lang.rust
  - samuelcolvin.jinjahtml
  - streetsidesoftware.code-spell-checker
  - tomoki1207.pdf
  - vscodevim.vim
  - vscoss.vscode-ansible
  - yzhang.markdown-all-in-one
...
