---
flatpak_apps:
  - name: com.discordapp.Discord
    remote: flathub
  - name: com.microsoft.Teams
    remote: flathub
  - name: com.slack.Slack
    remote: flathub
  - name: com.spotify.Client
    remote: flathub
  - name: org.videolan.VLC
    remote: flathub
flatpak_repos:
  - name: flathub
    url: https://flathub.org/repo/flathub.flatpakrepo
...
