---
- block:
  - name: install packages for editing Gnome 3 settings
    dnf:
      name:
        - glib2
        - dconf
      state: present
    become: True
    become_user: root

  # UI settings
  - name: enable minimize and maximize buttons
    command: gsettings set org.gnome.desktop.wm.preferences button-layout "appmenu:minimize,maximize,close"

  - name: make workspaces static
    command: gsettings set org.gnome.shell.overrides dynamic-workspaces false

  - name: set number of workspaces to four
    command: gsettings set org.gnome.desktop.wm.preferences num-workspaces 4

  # Touchpad settings
  - name: modify touchpad settings
    command: gsettings set org.gnome.desktop.peripherals.touchpad {{ item.key }} {{ item.value }}
    loop:
    # Enable two-finger scrolling
    - key: 'two-finger-scrolling-enabled'
      value: 'true'
    # Enable natural scrolling
    - key: 'natural-scroll'
      value: 'true'
    # Disable tap-to-click on touchpad
    - key: 'tap-to-click'
      value: 'false'
    # Use finger count to determine click type
    # Ex: one finger => left-click
    #     two fingers => right-click
    #     three fingers => middle-click
    - key: 'click-method'
      value: 'fingers'

  - name: backup current custom shortcuts
    shell: dconf dump /org/gnome/settings-daemon/plugins/media-keys/ > /tmp/media-keys.{{ ansible_date_time.epoch }}

  # NOTE: Using `dconf load` requires a user to logout before shortcuts will work.
  - name: load custom shortcuts
    shell: echo -e "{{ lookup('file', 'media-keys') }}" | dconf load /org/gnome/settings-daemon/plugins/media-keys/

  - debug:
      msg: "NOTE: You must logout before keyboard shortcuts will work."
  tags:
  - gnome3
...
